# Generated by Django 5.2.14 on 2026-08-21 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('confronto_direto', models.BooleanField(default=True, verbose_name='Confronto Direto')),
                ('vitorias', models.BooleanField(default=True, verbose_name='Número de Vitórias')),
                ('saldo_gols', models.BooleanField(default=True, verbose_name='Saldo de Gols')),
                ('gols_pro', models.BooleanField(default=False, verbose_name='Gols Marcados')),
                ('gol_fora', models.BooleanField(default=False, verbose_name='Gol Fora de Casa')),
                ('menor_vermelho', models.BooleanField(default=False, verbose_name='Menor nº de Cartões Vermelhos')),
                ('menor_amarelo', models.BooleanField(default=False, verbose_name='Menor nº de Cartões Amarelos')),
                ('federacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='core.federacao', verbose_name='Federação')),
            ],
            options={
                'verbose_name': 'Critério de Classificação',
                'verbose_name_plural': 'Critérios de Classificação',
                'ordering': ['nome'],
                'unique_together': {('federacao', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='FormatoCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('pontos_por_vitoria', models.PositiveSmallIntegerField(default=3, verbose_name='Pontos por vitória')),
                ('pontos_por_empate', models.PositiveSmallIntegerField(default=1, verbose_name='Pontos por empate')),
                ('permite_empate', models.BooleanField(default=True, verbose_name='Permite empate')),
                ('pontos_corridos', models.BooleanField(default=False, verbose_name='Pontos Corridos')),
                ('fase_grupos', models.BooleanField(default=False, verbose_name='Fase de Grupos')),
                ('mata_mata', models.BooleanField(default=False, verbose_name='Mata-Mata')),
                ('turnos', models.PositiveSmallIntegerField(choices=[(1, 'Turno único'), (2, 'Ida e volta')], default=1, verbose_name='Turnos')),
                ('prorrogacao', models.BooleanField(default=False, verbose_name='Prorrogação')),
                ('penaltis', models.BooleanField(default=False, verbose_name='Disputa por Pênaltis')),
                ('qtd_times', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Quantidade de Times')),
                ('federacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='core.federacao', verbose_name='Federação')),
            ],
            options={
                'verbose_name': 'Formato de Competição',
                'verbose_name_plural': 'Formatos de Competição',
                'ordering': ['nome'],
                'unique_together': {('federacao', 'nome')},
            },
        ),
    ]
