# Generated by Django 5.2.14 on 2026-08-21 18:15

import apps.criterios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioclassificacao',
            name='ordem_criterios',
            field=models.JSONField(blank=True, default=apps.criterios.models._ordem_padrao),
        ),
    ]
