# Generated by Django 5.2.14 on 2026-08-21 17:18

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=300, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=10, verbose_name='Sigla')),
                ('escudo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='equipe/escudo', variations={'thumbnail': {'height': 200, 'width': 200}})),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='Estado')),
                ('estadio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Estádio / Campo')),
                ('tecnico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Técnico')),
                ('cor_uniforme_principal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor Uniforme Principal')),
                ('cor_uniforme_alternativo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor Uniforme Alternativo')),
                ('fundacao', models.DateField(blank=True, null=True, verbose_name='Fundação')),
                ('data_filiacao', models.DateField(blank=True, null=True, verbose_name='Data de Filiação')),
                ('situacao', models.CharField(choices=[('filiado', 'Filiado'), ('em_regularizacao', 'Em Regularização'), ('suspenso', 'Suspenso'), ('desfiliado', 'Desfiliado')], default='em_regularizacao', max_length=20, verbose_name='Situação')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('cadastrado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.federacao', verbose_name='Federação')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='equipe/atleta', variations={'thumbnail': {'height': 200, 'width': 200}})),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('posicao', models.CharField(choices=[('GOLEIRO', 'Goleiro(a)'), ('ZAGUEIRO', 'Zagueiro(a)'), ('LATERAL_DIREIRO', 'Lateral Direito(a)'), ('LATERAL_ESQUERDO', 'Lateral Esquerdo(a)'), ('VOLANTE', 'Volante'), ('MEIO_CAMPO', 'Meio Campo'), ('MEIA_ATACANTE', 'Meio Atacante'), ('PONTA_DIREITA', 'Ponta Direita'), ('PONTA_ESQUERDA', 'Ponta Esquerda'), ('ATACANTE', 'Atacante')], max_length=30, verbose_name='Posição')),
                ('pe_dominante', models.CharField(blank=True, choices=[('DIREITO', 'Direito'), ('ESQUERDO', 'Esquerdo'), ('AMBIDESTRO', 'Ambidestro')], max_length=10, null=True, verbose_name='Pé Dominante')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 1.80', max_digits=4, null=True, verbose_name='Altura (m)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 75.50', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('situacao', models.CharField(choices=[('APTO', 'Apto'), ('LESIONADO', 'Lesionado'), ('FORA', 'Fora do Elenco')], default='APTO', max_length=10, verbose_name='Situação')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_jogador', to='equipe.equipe')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
    ]
