# Generated by Django 5.2.14 on 2026-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=10, verbose_name='Sigla')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='federacao/logos/')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Federação',
                'verbose_name_plural': 'Federações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioFederacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('SEC', 'Secretário'), ('ARB', 'Árbitro'), ('DIR', 'Dirigente de Clube')], default='DIR', max_length=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Federação',
                'verbose_name_plural': 'Vínculos Usuário-Federação',
            },
        ),
    ]
