# Generated by Django 5.2.14 on 2026-08-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofederacao',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirigentes', to='equipe.equipe', verbose_name='Clube gerenciado'),
        ),
        migrations.AddField(
            model_name='usuariofederacao',
            name='federacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.federacao'),
        ),
        migrations.AddField(
            model_name='usuariofederacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='federacoes',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='core.UsuarioFederacao', to='core.federacao'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariofederacao',
            unique_together={('usuario', 'federacao')},
        ),
    ]
