# Generated by Django 5.2.14 on 2026-08-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome / Descrição')),
                ('chave', models.CharField(editable=False, max_length=64, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chave de API',
                'verbose_name_plural': 'Chaves de API',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Amarelo', 'Cartão Amarelo'), ('Vermelho', 'Cartão Vermelho')], max_length=10)),
                ('minuto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['minuto'],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('tem_provisorio', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pontos', '-saldo_gols', '-vitorias'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pontos', '-saldo_gols', '-vitorias', '-gols_pro'],
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Final')),
                ('categoria', models.CharField(choices=[('adulto', 'Adulto'), ('master', 'Master'), ('sub20', 'Sub-20'), ('sub17', 'Sub-17'), ('sub15', 'Sub-15'), ('sub13', 'Sub-13'), ('sub11', 'Sub-11')], default='adulto', max_length=10, verbose_name='Categoria')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('misto', 'Misto')], default='masculino', max_length=15, verbose_name='Gênero')),
                ('modalidade', models.CharField(choices=[('campo', 'Futebol de Campo'), ('futsal', 'Futsal'), ('society', 'Society'), ('beach', 'Beach Soccer')], default='campo', max_length=10, verbose_name='Modalidade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('configurada', 'Configurada'), ('inscricoes', 'Inscrições Abertas'), ('inscricoes_encerradas', 'Inscrições Encerradas'), ('andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=25, verbose_name='Status')),
                ('data_abertura_inscricao', models.DateField(blank=True, null=True, verbose_name='Abertura de inscrições')),
                ('data_encerramento_inscricao', models.DateField(blank=True, null=True, verbose_name='Encerramento de inscrições')),
                ('limite_atletas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de atletas por equipe')),
                ('taxa_inscricao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taxa de inscrição (R$)')),
                ('pontos_vitoria_snap', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('pontos_empate_snap', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('permite_empate_snap', models.BooleanField(blank=True, editable=False, null=True)),
                ('penaltis_snap', models.BooleanField(blank=True, editable=False, null=True)),
                ('prorrogacao_snap', models.BooleanField(blank=True, editable=False, null=True)),
                ('turnos_snap', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('criterio_snap', models.JSONField(blank=True, editable=False, null=True)),
                ('qtd_classificados_por_grupo', models.PositiveIntegerField(default=2, verbose_name='Classificados por grupo')),
                ('grupos_ida_e_volta', models.BooleanField(default=False, verbose_name='Grupos: Ida e Volta')),
                ('limite_amarelos_suspensao', models.PositiveIntegerField(default=3, help_text='Quantidade de cartões amarelos que gera 1 jogo de suspensão', verbose_name='Amarelos p/ suspensão')),
                ('jogos_suspensao_amarelos', models.PositiveIntegerField(default=1, verbose_name='Jogos suspenso (amarelos)')),
                ('jogos_suspensao_vermelho', models.PositiveIntegerField(default=1, verbose_name='Jogos suspenso (vermelho)')),
            ],
        ),
        migrations.CreateModel(
            name='ConfrontoMatamate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_confronto', models.CharField(choices=[('normal', 'Normal'), ('terceiro', '3º Lugar')], default='normal', max_length=10, verbose_name='Tipo')),
                ('penaltis_mandante', models.PositiveIntegerField(blank=True, null=True)),
                ('penaltis_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EscalacaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camisa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº')),
                ('tipo', models.CharField(choices=[('titular', 'Titular'), ('reserva', 'Reserva')], default='titular', max_length=10)),
                ('capitao', models.BooleanField(default=False, verbose_name='Capitão')),
            ],
            options={
                'verbose_name': 'Escalação',
                'verbose_name_plural': 'Escalações',
                'ordering': ['equipe', 'tipo', 'numero_camisa', 'atleta__nome'],
            },
        ),
        migrations.CreateModel(
            name='EscalacaoTatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(default='4-3-3', max_length=20, verbose_name='Formação')),
                ('posicoes', models.JSONField(default=dict, verbose_name='Posições')),
                ('salvo_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escalação Tática',
                'verbose_name_plural': 'Escalações Táticas',
            },
        ),
        migrations.CreateModel(
            name='EscalacaoTaticaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(default='4-3-3', max_length=20, verbose_name='Formação')),
                ('posicoes', models.JSONField(default=dict, verbose_name='Posições')),
                ('confirmado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escalação Tática de Jogo',
                'verbose_name_plural': 'Escalações Táticas de Jogo',
            },
        ),
        migrations.CreateModel(
            name='EtapaKnockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semifinal', 'Semifinal'), ('terceiro', 'Disputa de 3º Lugar'), ('final', 'Final')], max_length=10)),
                ('ida_e_volta', models.BooleanField(default=False, verbose_name='Ida e Volta')),
                ('concluida', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0, editable=False)),
                ('origem', models.CharField(blank=True, choices=[('grupos', 'Classificados dos grupos'), ('etapa_anterior', 'Vencedores da etapa anterior'), ('liga', 'Classificados da liga')], default='', max_length=15, verbose_name='Fonte de vagas')),
            ],
            options={
                'verbose_name': 'Etapa Knockout',
                'verbose_name_plural': 'Etapas Knockout',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('liga', 'Pontos Corridos'), ('grupos', 'Fase de Grupos'), ('mata_mata', 'Mata-Mata')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fonte_tipo', models.CharField(choices=[('inscricao', 'Equipes inscritas'), ('fase_anterior', 'Classificados da fase anterior')], default='inscricao', max_length=15)),
                ('qtd_classificados', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('penalti', 'Pênalti'), ('contra', 'Gol Contra')], default='normal', max_length=10)),
            ],
            options={
                'ordering': ['minuto'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do grupo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('pontos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Histórico de Classificação',
                'ordering': ['rodada__numero', 'posicao'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camisa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Inscrição de Atleta',
                'verbose_name_plural': 'Inscrições de Atletas',
                'ordering': ['numero_camisa', 'atleta__nome'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True)),
                ('taxa_paga', models.BooleanField(default=False, verbose_name='Taxa paga')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
            ],
            options={
                'verbose_name': 'Inscrição de Equipe',
                'verbose_name_plural': 'Inscrições de Equipes',
                'ordering': ['equipe__nome_equipe'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('gols_casa', models.IntegerField(default=0)),
                ('gols_fora', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em andamento'), ('provisorio', 'Provisório'), ('finalizado', 'Finalizado'), ('homologado', 'Homologado'), ('anulado', 'Anulado')], default='agendado', max_length=15)),
                ('resultado_tipo', models.CharField(choices=[('normal', 'Normal'), ('wo_casa', 'W.O. da equipe mandante (visitante vence)'), ('wo_fora', 'W.O. da equipe visitante (mandante vence)')], default='normal', max_length=10, verbose_name='Tipo de resultado')),
                ('finalizado', models.BooleanField(default=False)),
                ('em_andamento', models.BooleanField(default=False, verbose_name='Em andamento')),
                ('anulado', models.BooleanField(default=False)),
                ('wo', models.BooleanField(default=False, verbose_name='W.O.')),
                ('publico', models.PositiveIntegerField(blank=True, null=True, verbose_name='Público presente')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do local')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('invasao', 'Invasão de campo'), ('briga', 'Briga / Tumulto'), ('arremesso', 'Arremesso de objetos'), ('cancelamento', 'Cancelamento / Abandono'), ('atraso', 'Atraso no início'), ('outro', 'Outro')], default='outro', max_length=15)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('minuto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minuto')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['minuto'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('desistiu_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Participação em Fase',
                'verbose_name_plural': 'Participações em Fases',
                'ordering': ['fase', 'seed'],
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubstituicaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Substituição',
                'verbose_name_plural': 'Substituições',
                'ordering': ['minuto'],
            },
        ),
        migrations.CreateModel(
            name='Sumula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('encerrada', 'Encerrada'), ('homologada', 'Homologada'), ('anulada', 'Anulada')], default='rascunho', max_length=15)),
                ('observacoes_arbitro', models.TextField(blank=True, verbose_name='Observações do árbitro')),
                ('homologada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Súmula',
                'verbose_name_plural': 'Súmulas',
            },
        ),
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('amarelos', 'Acúmulo de Cartões Amarelos'), ('vermelho', 'Cartão Vermelho')], default='amarelos', max_length=20)),
                ('rodadas_pendentes', models.PositiveIntegerField(default=1, verbose_name='Rodadas pendentes')),
                ('cumprida', models.BooleanField(default=False)),
                ('automatica', models.BooleanField(default=True, verbose_name='Gerada automaticamente')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ZonaClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('campeao', 'Campeão'), ('classificacao', 'Classificação para próxima fase'), ('acesso', 'Acesso (promoção à série superior)'), ('rebaixamento', 'Rebaixamento'), ('vaga_externa', 'Vaga para outra competição')], max_length=15)),
                ('faixa_inicio', models.PositiveIntegerField(verbose_name='Posição inicial')),
                ('faixa_fim', models.PositiveIntegerField(verbose_name='Posição final')),
                ('cor', models.CharField(default='#3b82f6', help_text='Cor hex para a borda na classificação (ex.: #3b82f6).', max_length=7)),
            ],
            options={
                'verbose_name': 'Zona de Classificação',
                'verbose_name_plural': 'Zonas de Classificação',
                'ordering': ['fase', 'faixa_inicio'],
            },
        ),
    ]
