# Generated by Django 5.2.14 on 2026-08-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competicao', '0001_initial'),
        ('core', '0001_initial'),
        ('criterios', '0001_initial'),
        ('equipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='federacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.federacao'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='equipe.atleta'),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='classificacaogrupo',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='competicao',
            name='criterio_classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competicoes', to='criterios.criterioclassificacao', verbose_name='Critério de Classificação'),
        ),
        migrations.AddField(
            model_name='competicao',
            name='federacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competicoes', to='core.federacao', verbose_name='Federação'),
        ),
        migrations.AddField(
            model_name='competicao',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competicoes', to='criterios.formatocompeticao', verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='confrontomatamate',
            name='equipe_mandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos_mandante', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='confrontomatamate',
            name='equipe_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos_visitante', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='confrontomatamate',
            name='vencedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos_vencidos', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='escalacaojogo',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes', to='equipe.atleta'),
        ),
        migrations.AddField(
            model_name='escalacaojogo',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='escalacaotatica',
            name='equipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalacao_tatica', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='escalacaotaticajogo',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalacoes_taticas_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalacaotaticajogo',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes_taticas_jogo', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='etapaknockout',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='confrontomatamate',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos', to='competicao.etapaknockout'),
        ),
        migrations.AddField(
            model_name='fase',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='fase',
            name='fonte_fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fases_seguintes', to='competicao.fase'),
        ),
        migrations.AddField(
            model_name='etapaknockout',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='competicao.fase'),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='competicao.fase'),
        ),
        migrations.AddField(
            model_name='gol',
            name='assistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias', to='equipe.atleta', verbose_name='Assistência'),
        ),
        migrations.AddField(
            model_name='gol',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gols', to='equipe.atleta'),
        ),
        migrations.AddField(
            model_name='gol',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='grupos_competicao', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='competicao.fase'),
        ),
        migrations.AddField(
            model_name='classificacaogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='competicao.grupo'),
        ),
        migrations.AddField(
            model_name='historicoclassificacao',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_posicoes', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='historicoclassificacao',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_posicoes', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='inscricaoatleta',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='equipe.atleta'),
        ),
        migrations.AddField(
            model_name='inscricaoatleta',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='inscricaoequipe',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_equipes', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='inscricaoequipe',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_competicao', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='competicao',
            name='equipes',
            field=models.ManyToManyField(related_name='competicoes_inscritas', through='competicao.InscricaoEquipe', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos', to='core.usuariofederacao', verbose_name='Árbitro'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='equipe_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='equipe_fora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='gol',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='escalacaotaticajogo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes_taticas_dirigente', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='confrontomatamate',
            name='jogo_ida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confronto_ida', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='confrontomatamate',
            name='jogo_volta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confronto_volta', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='local',
            name='federacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais', to='core.federacao', verbose_name='Federação'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos', to='competicao.local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='participacaofase',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_fase', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='participacaofase',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='competicao.fase'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rodadas', to='competicao.etapaknockout'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rodadas', to='competicao.fase'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rodadas', to='competicao.grupo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competicao.rodada'),
        ),
        migrations.AddField(
            model_name='historicoclassificacao',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_posicoes', to='competicao.rodada'),
        ),
        migrations.AddField(
            model_name='substituicaojogo',
            name='atleta_entrou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_jogo', to='equipe.atleta', verbose_name='Entrou'),
        ),
        migrations.AddField(
            model_name='substituicaojogo',
            name='atleta_saiu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_jogo', to='equipe.atleta', verbose_name='Saiu'),
        ),
        migrations.AddField(
            model_name='substituicaojogo',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_jogo', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='sumula',
            name='arbitro_assistente_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumulas_assistente1', to='core.usuariofederacao', verbose_name='1º Assistente'),
        ),
        migrations.AddField(
            model_name='sumula',
            name='arbitro_assistente_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumulas_assistente2', to='core.usuariofederacao', verbose_name='2º Assistente'),
        ),
        migrations.AddField(
            model_name='sumula',
            name='arbitro_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumulas_principal', to='core.usuariofederacao', verbose_name='Árbitro Principal'),
        ),
        migrations.AddField(
            model_name='sumula',
            name='homologada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumulas_homologadas', to=settings.AUTH_USER_MODEL, verbose_name='Homologada por'),
        ),
        migrations.AddField(
            model_name='sumula',
            name='jogo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sumula', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='sumula',
            name='quarto_arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumulas_quarto', to='core.usuariofederacao', verbose_name='4º Árbitro'),
        ),
        migrations.AddField(
            model_name='substituicaojogo',
            name='sumula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='competicao.sumula'),
        ),
        migrations.AddField(
            model_name='ocorrenciajogo',
            name='sumula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='competicao.sumula'),
        ),
        migrations.AddField(
            model_name='escalacaojogo',
            name='sumula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacao', to='competicao.sumula'),
        ),
        migrations.AddField(
            model_name='suspensao',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to='equipe.atleta'),
        ),
        migrations.AddField(
            model_name='suspensao',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='suspensao',
            name='jogos_cumpridos',
            field=models.ManyToManyField(blank=True, related_name='suspensoes_cumpridas', to='competicao.jogo'),
        ),
        migrations.AddField(
            model_name='zonaclassificacao',
            name='competicao_destino',
            field=models.ForeignKey(blank=True, help_text='Competição para onde as equipes desta faixa vão (acesso, rebaixamento ou vaga externa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_de_origem', to='competicao.competicao'),
        ),
        migrations.AddField(
            model_name='zonaclassificacao',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='competicao.fase'),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('competicao', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='etapaknockout',
            unique_together={('competicao', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('competicao', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='classificacaogrupo',
            unique_together={('grupo', 'equipe')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricaoatleta',
            unique_together={('competicao', 'atleta')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricaoequipe',
            unique_together={('competicao', 'equipe')},
        ),
        migrations.AlterUniqueTogether(
            name='escalacaotaticajogo',
            unique_together={('jogo', 'equipe')},
        ),
        migrations.AlterUniqueTogether(
            name='participacaofase',
            unique_together={('fase', 'equipe'), ('fase', 'seed')},
        ),
        migrations.AlterUniqueTogether(
            name='historicoclassificacao',
            unique_together={('competicao', 'equipe', 'rodada')},
        ),
        migrations.AlterUniqueTogether(
            name='escalacaojogo',
            unique_together={('sumula', 'atleta')},
        ),
    ]
