# Generated by Django 5.2.14 on 2026-08-21 17:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('equipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('titular', 'Titular'), ('emprestado', 'Emprestado')], default='titular', max_length=20)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_clubes', to='equipe.atleta')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atletas', to='equipe.equipe')),
            ],
            options={
                'verbose_name': 'Histórico de Clube',
                'verbose_name_plural': 'Históricos de Clubes',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='JanelaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janelas_transferencia', to='core.federacao')),
            ],
            options={
                'verbose_name': 'Janela de Transferência',
                'verbose_name_plural': 'Janelas de Transferência',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clube_origem_externo', models.CharField(blank=True, help_text='Nome do clube estrangeiro (para tipo=internacional).', max_length=150, verbose_name='Clube externo')),
                ('tipo', models.CharField(choices=[('definitiva', 'Definitiva'), ('emprestimo', 'Empréstimo'), ('retorno_emprestimo', 'Retorno de Empréstimo'), ('internacional', 'Internacional')], max_length=30)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='equipe.atleta')),
                ('clube_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='equipe.equipe')),
                ('clube_origem', models.ForeignKey(blank=True, help_text='Nulo apenas quando tipo=internacional (clube estrangeiro).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_saida', to='equipe.equipe')),
                ('janela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='registro.janelatransferencia')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFederativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_federativo', models.CharField(editable=False, max_length=30)),
                ('data_filiacao', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('transferido', 'Transferido'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_federativo', to='equipe.atleta')),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_federativos', to='core.federacao')),
            ],
            options={
                'verbose_name': 'Registro Federativo',
                'verbose_name_plural': 'Registros Federativos',
                'ordering': ['numero_federativo'],
                'unique_together': {('federacao', 'numero_federativo')},
            },
        ),
        migrations.CreateModel(
            name='SequenciaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('ultimo_seq', models.PositiveIntegerField(default=0)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencias_registro', to='core.federacao')),
            ],
            options={
                'verbose_name': 'Sequência de Registro',
                'verbose_name_plural': 'Sequências de Registro',
                'unique_together': {('federacao', 'ano')},
            },
        ),
    ]
