# Generated by Django 5.2.14 on 2026-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=40)),
                ('objeto_tipo', models.CharField(blank=True, help_text='Nome do modelo do objeto afetado (ex.: "competicao.Competicao").', max_length=60)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('registrado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('analytics', 'Análise de uso e desempenho'), ('marketing', 'Comunicações e marketing'), ('compartilhamento', 'Compartilhamento com parceiros'), ('dados_sensiveis', 'Tratamento de dados sensíveis')], max_length=25, verbose_name='Tipo')),
                ('aceito', models.BooleanField(default=False, verbose_name='Aceito')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
                'ordering': ['tipo'],
            },
        ),
    ]
