# Generated by Django 5.2.14 on 2026-08-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaevento',
            name='federacao',
            field=models.ForeignKey(blank=True, help_text='Federação onde o evento ocorreu (null para eventos globais).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='core.federacao'),
        ),
        migrations.AddField(
            model_name='auditoriaevento',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Quem executou a ação (null se automatizada).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentimentolgpd',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_lgpd', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['federacao', '-registrado_em'], name='auditoria_a_federac_838837_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['tipo', '-registrado_em'], name='auditoria_a_tipo_69c2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['objeto_tipo', 'objeto_id'], name='auditoria_a_objeto__cd0f88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consentimentolgpd',
            unique_together={('usuario', 'tipo')},
        ),
    ]
